login_app/urls.py
# file: todo_project/login_app/urls.py

from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
   path('login/', views.login, name='login'),
   path('logout/', views.logout, name='logout'),
   path('request_passowrd_request/', views.request_password_reset, name='request_password_reset'),
   path('password_reset/', views.password_reset, name='password_reset'),
   path('sign_up/', views.sign_up, name='sign_up'),
   path('delete_account/', views.delete_account, name='delete_account'),
    
]

todo_app/urls.py
# file: todo_project/todo_app/urls.py

from django.urls import path, include
from . import views
from .api import TodoList, TodoDetail

app_name = 'todo_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('change_status', views.change_status, name='change_status'),
    path('completed_todos/', views.completed_todos, name='completed_todos'),
    path('delete_todo', views.delete_todo, name='delete_todo'),
    path('api/v1/', TodoList.as_view()),
    path('api/v1/<int:pk>/', TodoDetail.as_view()),
    path('api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
]

todo_project/urls.py
# file: todo_project/todo_project/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo_app.urls')),
    path('accounts/', include('login_app.urls')),
]

login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.created_timestamp} - {self.updated_timestamp} - {self.token}'

todo_app/models.py
# file: todo_project/todo_app/models.py

from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.text} - {self.status}"

login_app/views.py
# file: todo_project/login_app/views.py

from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import PasswordResetRequest

def login(request):
    context = {}

    if request.method == "POST":
       
        username = request.POST['user']
        password = request.POST['password']
       
        user = authenticate(request, username=username, password=password)

        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('todo_app:index'))
        else:
            context = {
                'error': 'Bad username or password.'
            }
    return render(request, 'login_app/login.html', context)


def logout(request):
    dj_logout(request)
    return render(request, 'login_app/login.html')


def sign_up(request):
    context = {}

    if request.method == "POST":
        
        username = request.POST['user']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            if User.objects.create_user(username, email, password):
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                context = {
                    'error': 'Could not create user account - please try again.'        
                }
        else:
            context = {
                'error': 'Password did not match. Please try again.'
            }

    return render(request, 'login_app/sign_up.html', context);


def request_password_reset(request):
    
    if request.method == "POST":
        post_user = request.POST['username']
        user = None

        if post_user:
            try:
                user = User.objects.get(username=post_user)
            except:
                print(f'Invalid password request: {post_user}')
        else:
            post_user = request.POST['email']
            try:
                user = User.objects.get(email=post_user)
            except:
                print(f'Invalid password request: {post_user}')
        if user:
            prr = PasswordResetRequest()
            prr.user = user
            prr.save()
            print(prr)
            return HttpResponseRedirect(reverse('login_app:password_reset'))
    
    return render(request, 'login_app/request_password_reset.html')

def password_reset(request):
    if request.method == 'POST':
        post_user = request.POST['username']
        password = request.POST['password']
        confirm_password  = request.POST['confirm_password']
        token = request.POST['token']

        if password == confirm_password:
            try:
                prr = PasswordResetRequest.objects.get(token=token)
                prr.save()
            except:
                print('Invalid password reset attempt!')
                return render(request, 'login_app/passord_reset.html')

            user = prr.user
            user.set_password(password)
            user.save()
            return HttpResponseRedirect(reverse('login_app:login'))

    return render(request, 'login_app/password_reset.html')


@login_required
def delete_account(request):
    if request.method == "POST":
        if request.POST['confirm_deletion'] == "DELETE":
            user = authenticate(request, username=request.user, password=request.POST['password'])
            if user:
                print(f'Deleting user {user}')
                user.delete()
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                print("fail delete")

    return render(request, 'login_app/delete_account.html')
    

todo_app/views.py
# file: todo_project/todo_app/views.py

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.urls import reverse
from .models import Todo


def index(request):
    if request.method == "POST":
        text = request.POST["text"]
        todo = Todo()
        todo.text = text
        todo.user = request.user
        todo.save()

    todos = Todo.objects.filter(user=request.user, status=False)
    context = {
        'todos': todos
    }
    return render(request, 'todo_app/index.html', context)

def change_status(request):
    pk = request.POST['pk']
    todo = get_object_or_404(Todo, user=request.user, pk=pk)
    if "checked" in request.POST:
        todo.status = True
    else:
        todo.status =  False
    todo.save()
    return HttpResponseRedirect(reverse('todo_app:index'))

def completed_todos(request):
    todos = Todo.objects.filter(user=request.user, status=True)
    context = {
        'todos': todos
    }
    return render(request, 'todo_app/completed_todos.html', context)

def delete_todo(request):
    print(request.META['HTTP_REFERER'])
    pk = request.POST["pk"]
    todo = get_object_or_404(Todo, pk=pk)
    todo.delete()
    if request.META['HTTP_REFERER'].split('/')[-2] == 'todo':
        return HttpResponseRedirect(reverse('todo_app:index'))
    else:  
        return HttpResponseRedirect(reverse('todo_app:completed_todos'))

login_app/templates/login_app/delete_account.html
<!-- file: todo_project/login_app/templates/login_app/delete_account.html -->

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Delete Account</title>
</head>
<body>
   <h1>Delete Account</h1>
   <hr />
   <form action="{% url 'login_app:delete_account'%}" method="POST">
      {% csrf_token %}
      <input type="password" name="password" placeholder="Password">
      <br />
      <input type="text" name="confirm_deletion" placeholder="TYPE DELETE">
      <br />
      <button>Submit</button>
   </form>
   <hr />
</body>
</html>

login_app/templates/login_app/login.html
<!-- file: todo_project/login_app/templates/login_app/login.html -->

<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Login</title>
   </head>
   <body>
      <h1>Login</h1>
      <a href="{% url 'login_app:sign_up' %}">Sign Up</a>
      <hr />
      <form action="{% url 'login_app:login' %}" method="POST">
	 {% csrf_token %}
	 <input type="text" name="user" placeholder="User Name">
	 <input type="password" name="password" placeholder="Password">
	 <button>Login</button>
      </form>
      <hr />
      {% if error %}
      {{ error }}
      {% endif %}
      <a href="{% url 'login_app:request_password_reset' %}">Request Password Reset</a>
   </body>
</html>

login_app/templates/login_app/password_reset.html
<!-- file: todo_project/login_app/templates/login_app/password_reset.html -->

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Reset Password</title>
</head>
<body>
   <h1>Reset Password</h1>
   <hr />
   <form action="{% url 'login_app:password_reset' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="User Name">
      <br />
      <input type="password" name="password" placeholder="New Password">
      <br />
      <input type="password" name="confirm_password" placeholder="Repeat New Password">
      <br />
      <input type="text" name="token" placeholder="Token">
      <br />
      <button>Submit</button>
   </form>
   <hr />
</body>
</html>

login_app/templates/login_app/request_password_reset.html
<!-- file: todo_project/login_app/templates/login_app/request_password_reset.html -->

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Request Password Reset</title>
</head>
<body>
   <h1>Request Password Reset</h1>
   <hr />
      <form action="{% url 'login_app:request_password_reset' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="User Name">
            <br />
            <input type="email" name="email" placeholder="Email Address">
            <br />
            <button>Submit</button>
      </form>
   <hr />
</body>
</html>

login_app/templates/login_app/sign_up.html
<!-- file: todo_project/login_app/templates/login_app/sign_up.html -->

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Sign Up</title>
</head>
<body>
   <h1>Sign Up</h1>
   <hr />
   <form action="{% url 'login_app:sign_up' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="user" placeholder="User Name">
      <input type="email" name="email" placeholder="Email Address">
      <input type="password" name="password" placeholder="Password">
      <input type="password" name="confirm_password" placeholder="Confirm Password">
      <button>Sign Up</button>
   </form>
   <hr />
   {% if error %}
      {{ error }}
   {% endif %}
</body>
</html>

todo_app/templates/todo_app/base.html
<!-- file: todo_project/todo_app/templates/todo_app/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Todo</title>
</head>
<body>
   <h1>Todo</h1>
   <p>Welcome {{ user }} - <a href="{% url 'login_app:logout' %}">Log out</a> - <a href="{% url 'login_app:delete_account' %}">Delete Account</a></p>
      {% block content %}
      {% endblock %}
      {% block footer %}
      {% endblock %}
</body>
</html>

todo_app/templates/todo_app/completed_todos.html
<!-- file: todo_project/todo_app/templates/todo_app/completed_todos.html -->

{% extends "todo_app/base.html" %}

{% block content %}

      <hr />
	 <ul>
	 {% for todo in todos  %}
	       <li>
		  <form action="{% url 'todo_app:change_status' %}" method="POST">
		     {% csrf_token %}
		     <input type="checkbox" name="checked" {% if todo.status %}checked{% endif %} >
		     <button>Update</button>
		     <button formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
		     <input type="hidden" name="pk" value="{{ todo.pk }}">
		     {{ todo.text }}
		  </form>
	       </li>
	 {% endfor %}
	 </ul>
      <hr />
{% endblock %}

{% block footer %}
<a href="{% url 'todo_app:index' %}">Todos</a>
{% endblock %}

todo_app/templates/todo_app/index.html
<!-- file todo_project/todo_app/templates/todo_app/index.html -->
<!-- file: todo_project/todo_app/templates/todo_app/index.html -->

{% extends "todo_app/base.html" %}

{% block content %}
      <hr />
      <ul>
	 {% for todo in todos  %}
	 <li>
	    <form action="{% url 'todo_app:change_status' %}" method="POST">
	       {% csrf_token %}
	       <input type="checkbox" name="checked" {% if todo.status %}checked{% endif %} >
	       <button>Update</button>
	       <button formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
	       <input type="hidden" name="pk" value="{{ todo.pk }}">
	       {{ todo.text }}
	    </form>	   
	 </li>
	 {% endfor  %}
      </ul>
      <hr />
      <form action="." method="POST">
	 {% csrf_token %}
	 <input type="text" name="text" placeholder="Write your todo item here!" />
	 <button>Create todo</button>
      </form>
      <a href="{% url 'todo_app:completed_todos' %}">Completed Todos</a>
{% endblock %}